export const INCREASE_BITCOIN_PRICE = "INCREASE_BITCOIN_PRICE";
export const DECREASE_BITCOIN_PRICE = "DECREASE_BITCOIN_PRICE";
export const SET_BITCOIN_RATIO = "SET_BITCOIN_RATIO";

export const BUY_BITCOIN = "BUY_BITCOIN";
export const SELL_BITCOIN = "SELL_BITCOIN";
export const SET_USER_BITCOINS = "SET_USER_BITCOINS";

export const DEPOSIT = "DEPOSIT";
export const WITHDRAW = "WITHDRAW";
export const SET_USER_MONEY = "SET_USER_MONEY";

export const SET_HISTORY_MESSAGE = "SET_HISTORY_MESSAGE";
export const HISTORY_EVENT = "HISTORY_EVENT";

export const ERROR = "ERROR";